"""criacao_inicial

Revision ID: 6d19990c1eab
Revises: 
Create Date: 2026-05-04 12:45:44.612772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d19990c1eab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas_board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('fixado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_board_id'), 'notas_board', ['id'], unique=False)
    op.create_table('patrimonios',
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('setor_atual', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('numero')
    )
    op.create_index(op.f('ix_patrimonios_numero'), 'patrimonios', ['numero'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha_hash', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('escopos_override', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('historico_movimentacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patrimonio_numero', sa.String(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('acao', sa.String(), nullable=False),
    sa.Column('origem', sa.String(), nullable=True),
    sa.Column('destino', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patrimonio_numero'], ['patrimonios.numero'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_movimentacoes_id'), 'historico_movimentacoes', ['id'], unique=False)
    op.create_table('transferencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patrimonio_numero', sa.String(), nullable=False),
    sa.Column('setor_origem', sa.String(), nullable=False),
    sa.Column('setor_destino', sa.String(), nullable=False),
    sa.Column('responsavel_recebimento', sa.String(), nullable=False),
    sa.Column('justificativa', sa.String(), nullable=True),
    sa.Column('numero_movimento', sa.String(length=50), nullable=True),
    sa.Column('efetivado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_admin', sa.Boolean(), nullable=True),
    sa.Column('motivo_override', sa.String(), nullable=True),
    sa.Column('assinatura_transferidor_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assinatura_recebedor_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patrimonio_numero'], ['patrimonios.numero'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transferencias_id'), 'transferencias', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transferencias_id'), table_name='transferencias')
    op.drop_table('transferencias')
    op.drop_index(op.f('ix_historico_movimentacoes_id'), table_name='historico_movimentacoes')
    op.drop_table('historico_movimentacoes')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_patrimonios_numero'), table_name='patrimonios')
    op.drop_table('patrimonios')
    op.drop_index(op.f('ix_notas_board_id'), table_name='notas_board')
    op.drop_table('notas_board')
    # ### end Alembic commands ###
