version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_almoxarifado
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha_super_segura
      POSTGRES_DB: almoxarifado_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: